let variant_list_data = [
    {
        name: "Lockout",
        credit: "Initial draft made by Flesh, updated & maintained by Tim, jacks, marlin, truegen, amber, Spirity, aco, crab, others",
        description: "Two players compete to finish a board of 25 squares. First to tick 13 objectives wins. If one person ticks an objective, the other may not tick it. Prologue cutscenes are not skippable. Standard custom progression rules apply.",
        notes:"The main competitive gamemode and form of Celeste bingo. Highly conducive to strategy.",
        color:"White",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Blackout",
        credit: "Various",
        description: "One or multiple teams of players race to complete a full bingo board of 25 objectives. Prologue cutscenes are not skippable. Standard custom progression rules apply.",
        notes:"The main non-competitive gamemode of Celeste bingo. Less intensive but still reliant on routing. A different generator is used if teams consist of only one player.",
        color:"White",
        tags:["blackout"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Ktango (Lockout)",
        credit: "Piano, named ‘ktango’ by metagloria, popularized by various",
        description: "Two teams of two players play on a bingo board of 25 objectives. Each team has a router, who may see the board, and a player, who cannot see the board but must play the game and get objectives. The router and the player communicate in a voice chat, and the player streams their game footage so the router may tick objectives. The router may not communicate about the board. Standard lockout rules apply.",
        notes:"A ktango-based tournament was held in April 2022. Ktango is sometimes used as a way to teach new bingo routers about the game (Coachtango).",
        color:"White",
        tags:["lockout", "ktango"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:2,
        max_players_per_team:2,
    },
    {
        name: "Fog of War",
        credit: "Dragon512, plugin developed by Cirion, Rhuan, ported into Celeste Bingosync by crab",
        description: "A variant of blackout (teams or solo) in which only the lowest-tier objective on the 5x5 board is revealed at the start, and as players tick objectives on the bingo board, adjacent objectives are revealed. Standard blackout rules apply.",
        color:"White",
        tags:["blackout"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Masked Bingo",
        credit: "Fladervy, inspired by Age of Empires hidden cup",
        description: "A variant of lockout in which the two players are concealed from each other and any watchers.",
        notes:"A tournament of this style was organized for expert play in March 2021, and for advanced play in June 2021. An option in the BingoUI settings allows for in-game controls to be concealed for this gamemode.",
        color:"Purple",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "New Longo",
        credit: "Adapted from Old Longo by April, metagloria, crab, others",
        description: "A newer, more polished version of longo which fixes typos, removes some difficult objectives, and deletes most multi-chapter variant objectives, to make the game playable.",
        notes:"Almost exclusively played blackout.",
        color:"Purple",
        tags:["blackout", "long", "difficult"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Chairgo",
        credit: "metagloria",
        description: "Multiple players play on a bingo board with 25 objectives. While there are n players left, each player must tick at least ceil(10/n) objectives, or ceil(15/n) objectives in cheat mode. Players cannot tick extra objectives, and players may not tick the same objective. The last player to tick their required objectives is eliminated. A new card is generated, and play continues with n-1 players. With 3 players remaining, the game ends and the first, second, and third place finishers are determined in one round.",
        notes:"This gamemode is often played with cheat mode, which reduces round length and decreases reliance on execution. A full game with n people can take about 10*(n-2) minutes.",
        color:"Purple",
        tags:["long"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "3 Line Bingo",
        credit: "Inspired by various other bingo games",
        description: "A variant of solo blackout in which instead of completing the entire board, players are allowed to choose any three lines and complete them. Standard blackout rules apply.",
        notes:"Deceptively difficult to route and strategy-heavy.",
        color:"Purple",
        tags:["blackout"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Invasion",
        credit: "buhbai, inspired by Hollow Knight bingo",
        description: "A variant of lockout bingo in which additional rules are imposed to limit what objectives players can tick; see explanatory videos.",
        notes: "Even more reliant on strategy than lockout. Many games are heavily unbalanced from initial ticks. Various generators have been suggested (by Cirion, Piols, and others) for adapting bingo generation to be fair for invasion: none are widely accepted. This can be combined with ktango.",
        color:"Purple",
        external_links:[
            {
                name:"General Explanatory Video:",
                link:"https://youtu.be/0HRAjUbGwJo",
            },
            {
                name:"Celeste-Specific Explanatory Video (made by metagloria):",
                link:"https://www.youtube.com/watch?v=OE2887GqBiQ",
            }
        ],
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Lockout (2v2)",
        credit: "Tim",
        description: "A variant of lockout in which each team has two players. One of the two players must complete an objective for their team to tick it. Teammates may communicate.",
        notes:"An event of this style took place during February 2023. It has been suggested that the players on each team are required to alternate ticks.",
        color:"Purple",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:2,
        max_players_per_team:2,
    },
    {
        name: "Sinkout",
        credit: "metagloria, Cirion, Dragon",
        description: "A variant of blackout. Two players pick three ships (a 3x1, 2x1, and 2x1 contiguous block of objectives) on their own bingo board. These ships are hidden from the opponent. Players sit in the same VC, and attempt to complete objectives on their opponent's board to discover and sink all three of their opponent's ships. For exach objective completed, the opponent must confirm whether that objective was on a ship.",
        color:"Purple",
        tags:["blackout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },

    {
        name: "Ktango (Blackout)",
        credit: "jacks",
        description: "A mixture of ktango and blackout. One router sits in voice call with two players and routes them to complete a board of 25 objectives as fast as possible.",
        color:"Blue",
        tags:["blackout", "ktango"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:3,
        max_players_per_team:3,
    },
    {
        name: "Kt2ngo",
        credit: "metagloria",
        description: "A variant of ktango in which each team has three people, two routers and one player. Each router routes against an opposing router on a bingo board with 25 objectives, and both routers control the same player to work towards both boards. Routers are not allowed to communicate about their boards or give specific information about their opponent’s position. First team to 25 objectives wins.",
        color:"Blue",
        tags:["lockout", "ktango", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:3,
        max_players_per_team:3,
    },
    {
        name: "Kt3ngo",
        credit: "metagloria",
        description: "Identical to Kt2ngo, but the player also has their own board, so three boards are being played concurrently. First team to win two of three boards wins.",
        color:"Blue",
        tags:["lockout", "ktango", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:3,
        max_players_per_team:3,
    },
    {
        name: "Telektango",
        credit: "metagloria, with input from SuperZooper",
        description: "A variant of ktango in which each team has three people: A router, a communicator, and a player. The router is not allowed to look at the player’s screen: instead, they must communicate via DMs with the communicator, who can talk to the player and relay information both ways.",
        notes: "Originally known as ‘Celeste Bingo 2’. In some games, the router sits in a voice call with the opposing team’s communicator and player, to promote communicators to be more vague with their instructors.",
        color:"Blue",
        tags:["lockout", "ktango", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:3,
        max_players_per_team:3,
    },
    {
        name: "Old Longo (Blackout)",
        credit: "April, with input from various others",
        description: "A blackout version of the original longo generator. See Old Longo (Lockout).",
        color:"Blue",
        tags:["blackout", "long", "difficult"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Row Control",
        credit: "sonicyellow",
        description: "A variant of lockout in which players only need to ‘control’ three rows to claim victory. Players can control a row by getting any three objectives in that row.",
        color:"Blue",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "3 Line Draft",
        credit: "Unknown, first played by Tiyo, jerky",
        description: "A variant of 3 Line Bingo in which the three lines a player must complete are chosen by the opponent. All 6 chosen lines must be different. Choice goes in the order A, B, B, A, A, B.",
        color:"Blue",
        tags:["blackout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Draft Lockout",
        credit: "notEphim",
        description: "A variant of lockout in which players pick five objectives each that cannot be ticked by the opponent for the first 20 minutes of the match. Chosen objectives must be different. Choice goes in the order A, B, B, A, A, B, B, A, A, B.",
        color:"Blue",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Memoringo",
        credit: "SatelliteSam",
        description: "A variant of lockout in which after 1 minute, all objectives disappear from the board, requiring players to memorize all 25 objectives. A player can try to tick an objective at any point: if that objective is not something they have, they must untick the objective and wait in place for 1 minute.",
        notes:"The ability to make the board disappear is made possible by a plugin developed by SatelliteSam.",
        color:"Blue",
        external_links:[{
            name:"Plugin",
            file:"download-files/memoringo.js",
        }],
        tags:["lockout", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Cirion’s Cursed Bingo",
        credit: "Cirion",
        description: "Players play lockout (or blackout) bingo on a completely new generator and board of objectives.",
        notes:"A tournament for this generator (known as Blind Bingo Tournament) was hosted in August 2022. Despite its name, the generator is not incredibly cursed.",
        color:"Blue",
        external_links:[{
            name:"Generator",
            file:"download-files/cirions_cursed_bingo.json",
        }],
        tags:["lockout", "blackout", "difficult", "custom-generator"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Tringo",
        credit: "Xenoras",
        description: "A variant of lockout in which three players attempt to get as many objectives as possible. One player must get a majority of objectives to win: play continues until it is impossible for any player to be overtaken in objective count.",
        notes: "Despite many attempts, a balanced three-player competitive format for bingo has never been found. One variant of Tringo allows 2 players each to tick off an objective.",
        color:"Blue",
        tags:["lockout"],
        min_teams:3,
        max_teams:3,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Variants (Superdash)",
        credit: "None",
        description: "A variant of lockout or blackout in which players play superdash.",
        color:"Blue",
        tags:["lockout", "variants"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Variants (Superdash vs NG+)",
        credit: "None",
        description: "A variant of lockout or blackout in which one player plays superdash and the other plays New Game+ (with 2 dashes).",
        color:"Blue",
        tags:["lockout", "variants"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Rotationally Symmetric Ktango (RSK)",
        credit: "Cookie",
        description: "A truly heinous variant of ktango. There are 4 players: A, B, C, and D. Player A routes Player B. Player B routes player C. Player C routes Player D. Player D routes player A. The two pairs of router/player pairs (A/B with C/D and B/C with D/A) play lockout against each other on the same board. All players sit in the same voice call, with each person but their router muted. The winner is the single player who both wins the game they are routing and wins the game they are playing.",
        color:"Blue",
        tags:["lockout", "ktango", "cursed"],
        min_teams:4,
        max_teams:4,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "6x6 Longo",
        credit: "April",
        description: "A variant of longo meant to be played on a 6x6 board, with even longer objectives.",
        color:"Blue",
        tags:["blackout", "long", "difficult"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Cheat Mode Bingo",
        credit: "metagloria, with input from Reed, crab, Cirion",
        description: "A variant of lockout or blackout in which players begin by activating cheat mode, which lets them access any chapter. A new generator is created to balance accessibility and contain fun things like C-sides.",
        notes: "According to cheat mode rules, ‘Complete’ a chapter means completing all checkpoints, whereas any collectible (e.g. red hearts) can be obtained just in that checkpoint.",
        color: "Blue",
        tags: ["blackout", "lockout", "custom-generator", "difficult"],
        min_teams: 1,
        max_teams: null,
        min_players_per_team: 1,
        max_players_per_team: null,
    },
    {
        name: "Twitch Plays Ktango (TPK)",
        credit: "crab",
        description: "Requires exactly 6 people. One person is designated the ‘player’, while the other 5 are ‘routers’, each having a bingo board. The first router to complete 3 lines on their bingo board wins. All routers anonymously post instructions for the player in the same channel, ‘Twitch Chat’, and the player follows the most recently posted instruction, unless it is vetoed by a majority of players.",
        external_links:[{
            name:"Detailed Ruleset",
            link:"https://discord.com/channels/529677942393929749/1125096018317418627/1125215297364819988",
        }],
        color: "Blue",
        tags: ["ktango", "blackout"],
        min_teams: 6,
        max_teams: 6,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Predictiongo",
        credit: "ilikerandom",
        description: "Two players are given a board of 25 objectives and they must each make a list of times they expect the objectives to be ticked. A separate player plays the entire board blackout, and whoever’s guessed time for that objective is closest to when it is actually completed gets the objective. Whoever gets a majority of objectives wins.",
        color: "Blue",
        tags: [],
        min_teams: 3,
        max_teams: 3,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Minesweeper Bingo",
        credit: "Suggested by gnommis, metagloria, crab, oolimry, Cirion independently. Programmed/finalized by Cirion",
        description: "Teams have to tick all objectives that aren't bombs, while avoiding completing bomb objectives, players are required to tick all completed objectives. Except if the objective is known to be a bomb and required to complete an objective that is known to not be a bomb. Suggested size is 7x7 with 13 mines for 2+ players.",
        color:"Green",
        external_links:[{
            name:"Bookmark",
            file:"download-files/bingoMinesweeper.js",
        }],
        tags:["blackout"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },

    {
        name: "Fullgo",
        credit: "Epyc",
        description: "A variant of lockout bingo in which every square requires you to complete an extremely long objective from an entirely new save file. After completing and ticking an objective, that save file must be deleted. First to 13 wins.",
        color:"Red",
        external_links:[{
            name:"Generator",
            link:"https://discord.com/channels/529677942393929749/689529939975864453/1068274121290551386",
        }],
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },

    {
        name: "Lockout (1v2)",
        credit: "None",
        description: "A variant of lockout in which one team has two players and the other has one player. Standard lockout rules apply.",
        color:"Blue",
        notes:"Sometimes, the team of two players is allowed to communicate; sometimes, communication is prohibited.",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:2,
        player_count_override:3
    },

    {
        name: "Ktanego",
        credit: "Cirion",
        description: "A combination of KTANE (Keep Talking and Nobody Explodes) with bingo, including things like modules.",
        color:"Orange",
        notes:"Currently still a work in progress by Cirion.",
        tags:["blackout", "unplayable"],
        min_teams:1,
        max_teams:1,
        min_players_per_team:2,
        max_players_per_team:2
    }
]