let variant_list_data = [
    {
        name: "Lockout",
        credit: "Initial draft made by Flesh, updated & maintained by Tim, jacks, marlin, truegen, amber, Spirity, aco, crab, others",
        description: "Two players compete to finish a board of 25 squares. First to tick 13 objectives wins. If one person ticks an objective, the other may not tick it. Prologue cutscenes are not skippable. Standard custom progression rules apply.",
        notes:"The main competitive gamemode and form of Celeste bingo. Highly conducive to strategy.",
        color:"White",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Blackout",
        credit: "Various",
        description: "One or multiple teams of players race to complete a full bingo board of 25 objectives. Prologue cutscenes are not skippable. Standard custom progression rules apply.",
        notes:"The main non-competitive gamemode of Celeste bingo. Less intensive but still reliant on routing. A different generator is used if teams consist of only one player.",
        color:"White",
        tags:["blackout"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Ktango (Lockout)",
        credit: "Piano, named ‘ktango’ by metagloria, popularized by various",
        description: "Two teams of two players play on a bingo board of 25 objectives. Each team has a router, who may see the board, and a player, who cannot see the board but must play the game and get objectives. The router and the player communicate in a voice chat, and the player streams their game footage so the router may tick objectives. The router may not communicate about the board. Standard lockout rules apply.",
        notes:"A ktango-based tournament was held in April 2022. Ktango is sometimes used as a way to teach new bingo routers about the game (Coachtango).",
        color:"White",
        tags:["lockout", "ktango"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:2,
        max_players_per_team:2,
    },
    {
        name: "Fog of War",
        credit: "Dragon512, plugin developed by Cirion, Rhuan, ported into Celeste Bingosync by crab",
        description: "A variant of blackout (teams or solo) in which only the lowest-tier objective on the 5x5 board is revealed at the start, and as players tick objectives on the bingo board, adjacent objectives are revealed. Standard blackout rules apply.",
        color:"White",
        tags:["blackout"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Masked Bingo",
        credit: "Fladervy, inspired by Age of Empires hidden cup",
        description: "A variant of lockout in which the two players are concealed from each other and any watchers.",
        notes:"A tournament of this style was organized for expert play in March 2021, and for advanced play in June 2021. An option in the BingoUI settings allows for in-game controls to be concealed for this gamemode.",
        color:"Purple",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "New Longo",
        credit: "Adapted from Old Longo by April, metagloria, crab, others",
        description: "A newer, more polished version of longo which fixes typos, removes some difficult objectives, and deletes most multi-chapter variant objectives, to make the game playable.",
        notes:"Almost exclusively played blackout.",
        color:"Purple",
        tags:["blackout", "long", "difficult"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Chairgo",
        credit: "metagloria",
        description: "Multiple players play on a bingo board with 25 objectives. While there are n players left, each player must tick at least ceil(10/n) objectives, or ceil(15/n) objectives in cheat mode. Players cannot tick extra objectives, and players may not tick the same objective. The last player to tick their required objectives is eliminated. A new card is generated, and play continues with n-1 players. With 3 players remaining, the game ends and the first, second, and third place finishers are determined in one round.",
        notes:"This gamemode is often played with cheat mode, which reduces round length and decreases reliance on execution. A full game with n people can take about 10*(n-2) minutes.",
        color:"Purple",
        tags:["long"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "3 Line Bingo",
        credit: "Inspired by various other bingo games",
        description: "A variant of solo blackout in which instead of completing the entire board, players are allowed to choose any three lines and complete them. Standard blackout rules apply.",
        notes:"Deceptively difficult to route and strategy-heavy.",
        color:"Purple",
        tags:["blackout"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Invasion",
        credit: "buhbai, inspired by Hollow Knight bingo",
        description: "A variant of lockout bingo in which additional rules are imposed to limit what objectives players can tick; see explanatory videos.",
        notes: "Even more reliant on strategy than lockout. Many games are heavily unbalanced from initial ticks. Various generators have been suggested (by Cirion, Piols, and others) for adapting bingo generation to be fair for invasion: none are widely accepted. This can be combined with ktango.",
        color:"Purple",
        external_links:[
            {
                name:"General Explanatory Video:",
                link:"https://youtu.be/0HRAjUbGwJo",
            },
            {
                name:"Celeste-Specific Explanatory Video (made by metagloria):",
                link:"https://www.youtube.com/watch?v=OE2887GqBiQ",
            }
        ],
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Lockout (2v2)",
        credit: "Tim",
        description: "A variant of lockout in which each team has two players. One of the two players must complete an objective for their team to tick it. Teammates may communicate.",
        notes:"An event of this style took place during February 2023. It has been suggested that the players on each team are required to alternate ticks.",
        color:"Purple",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:2,
        max_players_per_team:2,
    },
    {
        name: "Sinkout",
        credit: "metagloria, Cirion, Dragon",
        description: "A variant of blackout. Two players pick three ships (a 3x1, 2x1, and 2x1 contiguous block of objectives) on their own bingo board. These ships are hidden from the opponent. Players sit in the same VC, and attempt to complete objectives on their opponent's board to discover and sink all three of their opponent's ships. For exach objective completed, the opponent must confirm whether that objective was on a ship.",
        color:"Purple",
        tags:["blackout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },

    {
        name: "Ktango (Blackout)",
        credit: "jacks",
        description: "A mixture of ktango and blackout. One router sits in voice call with two players and routes them to complete a board of 25 objectives as fast as possible.",
        color:"Blue",
        tags:["blackout", "ktango"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:3,
        max_players_per_team:3,
    },
    {
        name: "Kt2ngo",
        credit: "metagloria",
        description: "A variant of ktango in which each team has three people, two routers and one player. Each router routes against an opposing router on a bingo board with 25 objectives, and both routers control the same player to work towards both boards. Routers are not allowed to communicate about their boards or give specific information about their opponent’s position. First team to 25 objectives wins.",
        color:"Blue",
        tags:["lockout", "ktango", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:3,
        max_players_per_team:3,
    },
    {
        name: "Kt3ngo",
        credit: "metagloria",
        description: "Identical to Kt2ngo, but the player also has their own board, so three boards are being played concurrently. First team to win two of three boards wins.",
        color:"Blue",
        tags:["lockout", "ktango", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:3,
        max_players_per_team:3,
    },
    {
        name: "Telektango",
        credit: "metagloria, with input from SuperZooper",
        description: "A variant of ktango in which each team has three people: A router, a communicator, and a player. The router is not allowed to look at the player’s screen: instead, they must communicate via DMs with the communicator, who can talk to the player and relay information both ways.",
        notes: "Originally known as ‘Celeste Bingo 2’. In some games, the router sits in a voice call with the opposing team’s communicator and player, to promote communicators to be more vague with their instructors.",
        color:"Blue",
        tags:["lockout", "ktango", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:3,
        max_players_per_team:3,
    },
    {
        name: "Old Longo (Blackout)",
        credit: "April, with input from various others",
        description: "A blackout version of the original longo generator. See Old Longo (Lockout).",
        color:"Blue",
        tags:["blackout", "long", "difficult"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Row Control",
        credit: "sonicyellow",
        description: "A variant of lockout in which players only need to ‘control’ three rows to claim victory. Players can control a row by getting any three objectives in that row.",
        color:"Blue",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "3 Line Draft",
        credit: "Unknown, first played by Tiyo, jerky",
        description: "A variant of 3 Line Bingo in which the three lines a player must complete are chosen by the opponent. All 6 chosen lines must be different. Choice goes in the order A, B, B, A, A, B.",
        color:"Blue",
        tags:["blackout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Draft Lockout",
        credit: "notEphim",
        description: "A variant of lockout in which players pick five objectives each that cannot be ticked by the opponent for the first 20 minutes of the match. Chosen objectives must be different. Choice goes in the order A, B, B, A, A, B, B, A, A, B.",
        color:"Blue",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Memoringo",
        credit: "SatelliteSam",
        description: "A variant of lockout in which after 1 minute, all objectives disappear from the board, requiring players to memorize all 25 objectives. A player can try to tick an objective at any point: if that objective is not something they have, they must untick the objective and wait in place for 1 minute.",
        notes:"The ability to make the board disappear is made possible by a plugin developed by SatelliteSam.",
        color:"Blue",
        external_links:[{
            name:"Plugin",
            file:"download-files/memoringo.js",
        }],
        tags:["lockout", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Cirion’s Cursed Bingo",
        credit: "Cirion",
        description: "Players play lockout (or blackout) bingo on a completely new generator and board of objectives.",
        notes:"A tournament for this generator (known as Blind Bingo Tournament) was hosted in August 2022. Despite its name, the generator is not incredibly cursed.",
        color:"Blue",
        external_links:[{
            name:"Generator",
            file:"download-files/cirions_cursed_bingo.json",
        }],
        tags:["lockout", "blackout", "difficult", "custom-generator"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Tringo",
        credit: "Xenoras",
        description: "A variant of lockout in which three players attempt to get as many objectives as possible. One player must get a majority of objectives to win: play continues until it is impossible for any player to be overtaken in objective count.",
        notes: "Despite many attempts, a balanced three-player competitive format for bingo has never been found. One variant of Tringo allows 2 players each to tick off an objective.",
        color:"Blue",
        tags:["lockout"],
        min_teams:3,
        max_teams:3,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Variants (Superdash)",
        credit: "None",
        description: "A variant of lockout or blackout in which players play superdash.",
        color:"Blue",
        tags:["lockout", "variants"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Variants (Superdash vs NG+)",
        credit: "None",
        description: "A variant of lockout or blackout in which one player plays superdash and the other plays New Game+ (with 2 dashes).",
        color:"Blue",
        tags:["lockout", "variants"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Rotationally Symmetric Ktango (RSK)",
        credit: "Cookie",
        description: "A truly heinous variant of ktango. There are 4 players: A, B, C, and D. Player A routes Player B. Player B routes player C. Player C routes Player D. Player D routes player A. The two pairs of router/player pairs (A/B with C/D and B/C with D/A) play lockout against each other on the same board. All players sit in the same voice call, with each person but their router muted. The winner is the single player who both wins the game they are routing and wins the game they are playing.",
        color:"Blue",
        tags:["lockout", "ktango", "cursed"],
        min_teams:4,
        max_teams:4,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "6x6 Longo",
        credit: "April",
        description: "A variant of longo meant to be played on a 6x6 board, with even longer objectives.",
        color:"Blue",
        tags:["blackout", "long", "difficult"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Cheat Mode Bingo",
        credit: "metagloria, with input from Reed, crab, Cirion",
        description: "A variant of lockout or blackout in which players begin by activating cheat mode, which lets them access any chapter. A new generator is created to balance accessibility and contain fun things like C-sides.",
        notes: "According to cheat mode rules, ‘Complete’ a chapter means completing all checkpoints, whereas any collectible (e.g. red hearts) can be obtained just in that checkpoint.",
        color: "Blue",
        tags: ["blackout", "lockout", "custom-generator", "difficult"],
        min_teams: 1,
        max_teams: null,
        min_players_per_team: 1,
        max_players_per_team: null,
    },
    {
        name: "Twitch Plays Ktango (TPK)",
        credit: "crab",
        description: "Requires exactly 6 people. One person is designated the ‘player’, while the other 5 are ‘routers’, each having a bingo board. The first router to complete 3 lines on their bingo board wins. All routers anonymously post instructions for the player in the same channel, ‘Twitch Chat’, and the player follows the most recently posted instruction, unless it is vetoed by a majority of players.",
        external_links:[{
            name:"Detailed Ruleset",
            link:"https://discord.com/channels/529677942393929749/1125096018317418627/1125215297364819988",
        }],
        color: "Blue",
        tags: ["ktango", "blackout"],
        min_teams: 6,
        max_teams: 6,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Predictiongo",
        credit: "ilikerandom",
        description: "Two players are given a board of 25 objectives and they must each make a list of times they expect the objectives to be ticked. A separate player plays the entire board blackout, and whoever’s guessed time for that objective is closest to when it is actually completed gets the objective. Whoever gets a majority of objectives wins.",
        color: "Blue",
        tags: ["cursed"],
        min_teams: 3,
        max_teams: 3,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "4x4 Bingo",
        credit: "talia",
        description: "Two players are given a board of 25 objectives. One player chooses a row or column to delete from the board, then the other player chooses a column or row to delete from the board. Players play lockout on the 16 remaining objectives.",
        notes: "It has been suggested that the objective in both the selected row and column could also be allowed to be played, so that there are 17 objectives and ties are no longer possible.",
        color: "Blue",
        tags: ["lockout"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Symmetrical Ktango",
        credit: "notEphim",
        description: "A variant of ktango in which teams of players route each other to have their partner complete objectives on a board that only they can see. Can be played lockout, blackout, or 3 line.",
        color: "Green",
        tags: ["lockout", "blackout", "ktango", "cursed"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 2,
    },
    {
        name: "Reverse Kt3ngo",
        credit: "Unknown",
        description: "Identical to Kt3ngo, but instead of each team having 2 routers and 1 player, each team has 1 router and 2 players, and the routers can tick anything that either of their players do. First team to win two of three boards wins.",
        color: "Green",
        tags: ["lockout", "ktango", "cursed"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 3,
        max_players_per_team: 3,
    },
    {
        name: "Ktango Taboo",
        credit: "metagloria",
        description: "A more strict version of ktango in which routers cannot say any of the words on the bingo board, but must allude to objectives to route the player.",
        color: "Green",
        tags: ["lockout", "ktango"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 2,
        max_players_per_team: 2,
    },
    {
        name: "3 Board Lockout",
        credit: "April, roofon",
        description: "A variant of lockout in which the players play three boards at once, and the first to complete two boards wins.",
        color: "Green",
        tags: ["lockout", "cursed"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Follow the Leadergo",
        credit: "metagloria",
        description: "Multiple players (more than 2) play on a bingo board with 25 objectives. One person is designated the ‘leader’ and declares an objective that all players must go for. The leader may not tick that objective. The first person to tick the declared objective becomes the new leader, and declares another objective which everyone must go for. Play continues until all 25 objectives are declared and ticked.",
        color: "Green",
        tags: ["blackout"],
        min_teams: 1,
        max_teams: null,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Variants (100x Dash Speed)",
        credit: "Cirion",
        description: "A variant of lockout in which players play with 100x dash speed.",
        notes: "Setting dash speed to 100x requires use of the Extended Variants mod. A custom generator is used to remove many impossible objectives.",
        color: "Green",
        external_links:[{
            name:"Generator",
            file:"download-files/100x_dash_speed.json",
        }],
        tags: ["lockout", "variants", "custom-generator", "difficult"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Variants (0 Gravity)",
        credit: "Cirion, Generator by RandomName",
        description: "A variant of lockout in which players play with 0 gravity.",
        notes: "Setting 0 gravity requires use of the Extended Variants mod. A custom generator is used to remove many impossible objectives.",
        color: "Green",
        external_links:[{
            name:"Generator",
            file:"download-files/0_gravity.json",
        }],
        tags: ["lockout", "variants", "custom-generator", "difficult"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Reed's Cursed Bingo",
        credit: "Reed",
        description: "Players play lockout (or blackout) bingo on a completely new cursed generator and board of objectives.",
        notes: "Unbalanced.",
        color: "Green",
        external_links:[{
            name:"Generator",
            file:"download-files/reeds_cursed_bingo.json",
        }],
        tags: ["lockout", "custom-generator", "difficult", "cursed"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Individual Berry Bingo",
        credit: "metagloria",
        description: "Players play lockout bingo on a custom generator, each objective of which contains only a single collectible (berry, binos, PICO-8 berry, or heart).",
        notes: "Unbalanced. Use the Randomized setting to create a board, not the srlv5 setting.",
        color: "Green",
        external_links:[{
            name:"Generator",
            file:"download-files/individual_berry_bingo.json",
        }],
        tags: ["lockout", "custom-generator"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "4-In-A-Row",
        credit: "metagloria, Reed",
        description: "A variant of lockout in which players need to tick any four objectives in a row to claim victory. If it is impossible for either player to win, the game ends in a draw.",
        notes: "Wraparounds may or may not be allowed.",
        color: "Green",
        tags: ["lockout"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Postage Stamp Bingo",
        credit: "metagloria, Reed",
        description: "A variant of lockout in which players need to tick any four objectives in a square to claim victory. If it is impossible for either player to win, the game ends in a draw.",
        notes: "Wraparounds may or may not be allowed.",
        color: "Green",
        tags: ["lockout"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "B3ngo",
        credit: "metagloria",
        description: "A variant of lockout in which three players play. Three boards are generated, and each player plays on two boards at the same time, forming a cycle. Play continues until all objectives are ticked, and whoever has the most objectives in total wins.",
        color: "Green",
        tags: ["lockout", "cursed"],
        min_teams: 3,
        max_teams: 3,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Spring Collab Bingo (Springo)",
        credit: "hydrei, metagloria",
        description: "A variant of lockout bingo played on the 2020 Spring Collab mod.",
        notes: "A generator was never finished, but many objectives for the Beginner section were made.",
        color: "Green",
        external_links:[{
            name:"Generator Scraps",
            file:"https://docs.google.com/spreadsheets/d/16YVIat4UIjuy_TvXCU9RX03_3fGmi5et0qN_ElduQik/edit#gid=497655973",
        }],
        tags: ["lockout", "custom-generator", "unplayable"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Old Longo (Lockout)",
        credit: "April, metagloria, with input from various others",
        description: "A variant of lockout bingo with objectives that are longer than usual, including objectives from multiple B-sides, in-game variants, and Chapter 9.",
        notes: "Originally created as a joke, old longo eventually grew in popularity and was updated to new longo. In general, it is inadvised to play the original old longo without practice, as some objectives are extremely difficult and/or variant-heavy.",
        color: "Green",
        tags: ["lockout", "custom-generator", "difficult", "long"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Crow Control Bingo",
        credit: "Azula, wiz independently",
        description: "An application of the ‘Crow Control’ Celeste mod to bingo. Two players play bingo while both games are hooked up to a single twitch stream, in which viewers may spawn obstacles or cause the players to gain variants, die, or become invincible.",
        color: "Green",
        tags: ["lockout", "long"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Old Lockout",
        credit: "None",
        description: "A variant of lockout in which players play on the old lockout generator from before chapter 9 was released. Players do not play with custom progression. Prologue cutscenes are unskippable.",
        notes: "The generator for this is improperly formatted. If you'd like to play this variant, feel free to reformat the generator to a json and ping @lightningreed133 with the updated version.",
        color: "Green",
        external_links:[{
            name:"Generator",
            file:"download-files/old_lockout.txt",
        }],
        tags: ["lockout", "long", "unplayable"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Line Lockout",
        credit: "RandomName",
        description: "A variant of lockout in which one player attempts to get a single line (5 objectives in a row) and the other player tries to stop them.",
        notes: "Favors the player attempting to block the line.",
        color: "Green",
        tags: ["lockout"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "25 Objective Draft",
        credit: "metagloria",
        description: "A variant of lockout in which players begin by picking all objectives on the board from the generator of 200+ objectives. Players alternate picking objectives from each of the generator’s 25 tiers: once an objective from a tier has been chosen, no other objective from that tier can be chosen. Once all 25 objectives are chosen, normal lockout play begins.",
        color: "Green",
        tags: ["lockout"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Adjacent Pair Bingo",
        credit: "metagloria",
        description: "A variant of lockout bingo in which players must tick pairs of adjacent objectives simultaneously. If there are no remaining such pairs, any objectives may be ticked. First to 13 wins.",
        color: "Green",
        tags: ["lockout"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Bingo but Canon",
        credit: "Reed",
        description: "A variant of lockout bingo in which each player has a ‘life’ counter starting at 1. Collecting a 1-UP increases a player’s life counter by 1. Dying reduces a player’s life counter by 1. If a player’s life counter drops to 0, they must delete their file and start a new file, replaying prologue.",
        color: "Green",
        tags: ["lockout", "cursed", "difficult"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Farewell Bingo",
        credit: "Cookie",
        description: "A variant of lockout in which all the objectives are in Farewell.",
        color: "Green",
        external_links:[{
            name:"Generator + Additional Ruleset",
            link:"https://docs.google.com/document/d/1_saXKc-ucMCS7203HLUcBEr70KLff6xkXeY_WLMCIOg/edit",
        }],
        tags: ["lockout", "short", "custom-generator"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Bingo???",
        credit: "Reed, ad",
        description: "A variant of lockout bingo in which objectives are taken literally and can be completed in non-traditional ways. In addition, cheating is allowed and frequently encouraged. For example, a square reading \"Reflection A-Side\" may be completed by playing any A-Side mirrored, or players may tick \"Golden Ridge B-Side\" when actually in Resort.",
        color: "Green",
        tags: ["lockout", "cursed"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Bingobuthardtoread",
        credit: "RandomName",
        description: "A variant of lockout bingo in which objectives in the standard generator are replaced with objectives which require doing the exact same thing, but are significantly harder to understand or parse. As an example, \"10 Berries in 3 Chapters\" could be replaced with \"As many berries as exist in 2A Start, collected in a number of different chapters equal to the number of chapters containing snowballs\".",
        color: "Green",
        external_links:[{
            name:"Generator",
            file:"download-files/bingobuthardtoread.json",
        }],
        tags: ["lockout", "custom-generator", "cursed"],
        min_teams: 2,
        max_teams: 2,
        min_players_per_team: 1,
        max_players_per_team: 1,
    },
    {
        name: "Minesweeper Bingo",
        credit: "Cirion, previously suggested by gnommis, metagloria, crab, oolimry, independently",
        description: "A variant of blackout bingo in which some unknown objectives are marked mines, and ticked objectives reveal the number of adjacent mines. The goal is to tick all non-mine objectives. Objectives much be ticked when obtained. Ticking an objective with a mine instantly loses, unless that mine objective is required to complete a different non-mine objective.",
        notes: "It is suggested to play on a 7x7 board with 13+ mines.",
        color:"Green",
        external_links:[{
            name:"Bookmark",
            file:"download-files/bingoMinesweeper.js",
        }],
        tags:["blackout"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Bingo with Anti-Delaying",
        credit: "Linus",
        description: "A variant of lockout bingo in which a player may anti-delay objectives by ticking them off before getting them. If the opponent calls their bluff by completing an anti-delayed objective, the bluffer loses the game immediately. If the bluffer safely completes a bluffed objective, that objective can no longer be stolen. First to 13 real objectives wins.",
        color:"Green",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Invasion Racing",
        credit: "Unknown",
        description: "Two or four players start on opposing sides of the board. Each player must get an objective on the opposite side of the board from where they started, via invasion-like rules for building forward. If an objective is ticked off, no other player may tick it. Players may only tick one objective on each of the 5 rows (or columns) that they need to win.",
        color:"Green",
        tags:["lockout"],
        min_teams:2,
        max_teams:4,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Half-Fog Lockout",
        credit: "jacks",
        description: "A variant of lockout bingo with two players, one with better execution. The player with better execution plays using Fog of War spectator mode, where only the first two tiers of objectives are revealed at the start and ticking something reveals all adjacent squares. The player with worse execution sees the whole board to begin with.",
        notes: "There is currently no automatic way to reveal two starting objectives in the fog of war mode on Celeste Bingosync.",
        color:"Green",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Bingobutslightlylonger",
        credit: "Epyc",
        description: "A variant of lockout bingo with slightly longer objectives.",
        color:"Green",
        external_links:[{
            name:"Generator",
            link:"download-files/bingobutslightlylonger.json",
        }],
        tags:["lockout", "custom-generator", "long"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "One Way Lockout",
        credit: "RandomName",
        description: "An unbalanced variant of lockout bingo in which Player A cannot tick objectives that player B has, but Player B can. Whoever has more objectives when all 25 squares are ticked wins.",
        notes:"This directly favors Player B, making it ideal when players have a skill deficit.",
        color:"Green",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Chessgo",
        credit: "Cirion",
        description: "64 bingo objectives are placed on a chessboard. Normal chess pieces are also placed on the chess board. By completing an objective on a square, you may move a piece to that square (if that movement is valid by chess rules), and the objective on it gets refreshed. There is no turn order. Whoever captures the opponent’s king first wins.",
        color:"Green",
        tags:["lockout", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Asyncgo",
        credit: "rhelmot",
        description: "A variant of lockout bingo in which two people play all 25 objectives on a bingo board, and then ticks and lockouts are applied retroactively, so that players must route without knowing what their opponent’s route is. After both players have ticked all objectives, logs are examined to decide who won what objective. Whoever wins 13 or more objectives wins.",
        notes:"This can be played with one opponent being a TAS.",
        color:"Green",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Table Turf Bingo",
        credit: "FlyingLudicolo",
        description: "A variant of lockout bingo. Each team starts with an objective ticked on symmetrical sides of the board. Players may only tick objectives that are adjacent to an objective they already have (or diagonally if that objective is blocked off on all 4 sides). Most objectives ticked in a predetermined time limit win. One way to start the match is on a 10x5 board, where team 1 starts with r3c2 and team 2 starts with r3c9. When matches are played on a 7x7 board, team 1 starts with r5c2 and team 2 starts with r3c6.",
        color:"Green",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Untieredgo",
        credit: "Epyc, RandomName",
        description: "A variant of bingo where objectives are untiered, allowed for ridiculous amounts of synergy, multiple tier 25 objectives, or other silly stuff.",
        notes: "Due to the way probability works, most boards are nondescript and indeed indistinguishable from a normal lockout board. To play this, use the Randomized option on Celeste Bingosync.",
        color:"Green",
        external_links:[{
            name:"Generator",
            link:"download-files/untieredgo.json",
        }],
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Bingolf (Antibingo)",
        credit: "Cirion",
        description: "A variant of Any% in which a board of 25 bingo objectives containing things people do in Any% is revealed, and players must complete an Any% run without doing as few of these objectives as possible.",
        notes: "This has supposedly been played, but I have no clue where the generator is.",
        color:"Green",
        tags:["lockout", "custom-generator", "unplayable"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Infectiongo",
        credit: "bulletinfi",
        description: "A variant of lockout in which two players attempt to tick all 25 objectives. When an objective is ticked, all directly adjacent objectives belonging to the opponent are turned the color of that tick. Once all 25 objectives are ticked, the person with 13 or more objectives wins.",
        color:"Green",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Renegadego",
        credit: "Dragon",
        description: "A variant of lockout bingo in which getting 2 objectives next to a square automatically wins you that square.",
        color:"Green",
        tags:["lockout"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Community Generator",
        credit: "Cookie, with objectives suggested by about 20 different people",
        description: "A variant of lockout (or blackout) bingo in which players play with an entirely new set of objectives, created by the community.",
        notes: "Created more as a social experiment than an actual bingo variant. Has only ever been played blackout. Use the Randomized setting to generate the board.",
        color:"Green",
        external_links:[{
            name:"Generator",
            link:"download-files/community_generator.json",
        }],
        tags:["lockout", "blackout", "custom-generator"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Celeste Bingo Challenge",
        credit: "Random Name, Cookie",
        description: "A variant of lockout (or blackout) bingo in which players play with a list of obejctives that consists of short challenges. Cheat mode and debug mode are allowed, and savestates may be used for practice. Pause buffering is banned.",
        notes: "Use the Randomized setting to generate the board.",
        color:"Green",
        external_links:[{
            name:"Generator",
            link:"download-files/celeste_bingo_challenge.json",
        }],
        tags:["lockout", "blackout", "custom-generator", "difficult"],
        min_teams:1,
        max_teams:null,
        min_players_per_team:1,
        max_players_per_team:null,
    },
    {
        name: "Positive Negative Bingo",
        credit: "bulletinfi",
        description: "A variant of lockout in which players have 2 standard lockout boards. The first is played normally, but on the second board, players must tick off objectives immediately if completed. Objectives on the second board reduce a player’s score by 1. Whoever has more points when the first board is completed wins.",
        color:"Green",
        tags:["lockout", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Minibingo (Blitzgo)",
        credit: "metagloria",
        description: "A variant of lockout in which players play on the central 3x3 miniature board. Only these 9 objectives may be ticked. First to 5 objectives wins.",
        notes: "Often played when players do not have enough time for a complete bingo match. Highly imbalanced.",
        color:"Green",
        tags:["lockout", "short"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Strikego",
        credit: "Cirion",
        description: "A variant of lockout bingo in which when a player gets an objective, they may pick another objective to delete from the game. First to 7 wins.",
        color:"Green",
        tags:["lockout", "short"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },
    {
        name: "Othellgo or Bingothello",
        credit: "metagloria, Ninja independently",
        description: "A variant of lockout in which whenever a player ticks an objective, such that there is in one of the 8 cardinal directions only objectives belonging to the opponent, followed by an objective of the ticking player, then all objectives in between the player’s two objectives are turned the player’s color.",
        color:"Green",
        tags:["lockout", "cursed"],
        min_teams:2,
        max_teams:2,
        min_players_per_team:1,
        max_players_per_team:1,
    },

    {
        name: "Ktanego",
        credit: "Cirion",
        description: "A combination of KTANE (Keep Talking and Nobody Explodes) with bingo, including things like modules.",
        color:"Orange",
        notes:"Currently still a work in progress by Cirion.",
        tags:["blackout", "unplayable"],
        min_teams:1,
        max_teams:1,
        min_players_per_team:2,
        max_players_per_team:2
    }
]
